#' Generate posterior predictive intervals
#'
#' Generates posterior predictive intervals for log-normally, negative-binomially,
#' or multinomially
#' distributed survey data. Intervals calculated from distributions generated by
#' \link[pwsHerringBasa]{post.pred.lognorm}, \link[pwsHerringBasa]{post.pred.negbin},
#' and \link[pwsHerringBasa]{post.pred.multinom}.
#'
#' @param fname Character string giving file path to MCMC results for predicted survey data
#' @param var Vector of MCMC-derived variances for survey data (lognorm or negbin)
#' @param ess Vector of effective sample sizes (multinom only)
#' @param years Years fit by BASA model
#' @param nburn Length of burn-in period at beginning of markov chains
#' @param dist Assumed distribution of survey data. Supported inputs are
#' `lognorm`, `negbin`, and `multinom`
#' @param mask Years when survey data was not collected, avoids generating predictions
#' for those years
#'
#' @returns A tibble of 50% and 95% posterior predictive intervals for survey data.
#'

generate.post.pred <- function(fname, var, ess, years, nburn=1,
                               dist="lognorm", mask=NA){
  year <- NULL

  if(dist != "multinom"){
    data <- read.table(fname, header = FALSE, sep = ",", dec=".")[-c(1:nburn), 1:length(years)]
  } else if(dist == "multinom"){
    data <- read.csv(fname, header = FALSE, dec=".")[-c(1:nburn), ]*100
  }

  if(dist != "multinom"){
    # CLR: changed this if statement such that condition has length 1
    if(all(is.na(mask))){
      data[data == 0] <- NA
    } else {
      data[,mask] <- NA
    }
  }

  if(dist == "lognorm"){
    pp <- post.pred.lognorm(data, var)
  } else if(dist == "negbin"){
    pp <- post.pred.negbin(data, var)
  } else if(dist == "multinom"){
    pp <- post.pred.multinom(data, ess, nage = 10)
  } else {
    stop(paste(dist, "is not a supported distribution!"))
  }

  if(dist != "multinom"){
    colnames(pp) <- years
    out <- tibble::as_tibble(pp) %>%
      tidyr::pivot_longer(dplyr::everything(), names_to = "year", values_to = "data") %>%
      na.omit() %>%
      dplyr::group_by(year) %>%
      tidybayes::median_qi(data, .width = c(0.5, 0.95)) %>%
      print(n=150)
  } else if(dist == "multinom"){
    out <- pp
  }

  return(out)
}
